### PR TITLE
Solution for hw2

### PR DESCRIPTION
**Pull request by rutujapadgilwar**

### CODE REVIEW

**Review by huutribui — COMMENTED** [review]
Hi Rutuja,
For exercise 01, it is a good idea to put some duplicate codes into a function and reuse it. It will help your code looks cleaner and reusable for other cases.
For exercise 04, it would be great if you put the await inside a try-catch block. Doing that would help you to check for errors and the program will not crash if it encounters an error from the backend.
Other exercises look good to me.

**Comment by AdrikGG** [comment]
Your code is pretty good. It seems to work the majority of cases for each exercise. There are, however, some styling issues within your code, and I have some suggestions.

I noticed that within your 01-coins and 02-reverse implementations that you used the wrong equality operators (as per the style guide). Where you use `==` make sure to instead use `===` and where you use `!=` instead use `!==`.
Another style guide violation I noticed was your use of `var`. Make sure to instead use `let` for variables that you will reassign, and `const` for variables you do not reassign. On that note, I noticed you used `let` in situations where you should instead use `const`, (ex: line 7 in 02-reverse, all uses in 03-form).
Also, make sure to always use the `let` or `const` keywords when declaring variables, it's important for a number of reasons, (errors: line 10 and line 19 in 02-reverse).

For better code readability I suggest removing commented out code such as `console.log` (01-coins),  and removing blank space at the end of code blocks (ex: line 15 and line 22 in 02-reverse).

Lastly, if you are interested in working on your code any further, consider how your 02-reverse solution handles negative numbers and floats. Specifically, notice how `findlength = number.toString().length;` doesn't account for the negation symbol or decimal point, and essentially considers them to be digits.

I hope all this helps!

**Review by Pranav-PSU — COMMENTED** [review]
Hi Rutuja,

1. It is preferable to use let instead of var.

2. It is always preferable to use type="email" instead of type="text" for the email field because its input value is validated automatically to ensure that it is a properly formatted e-mail address.

3. if(newsletter === true) -> The expression in the if condition is always executed first, and the condition is then executed based on its value because the expression is already boolean, if(newsletter) could have been used instead.

The rest of the work is excellent and nicely done.

**Comment by JeremyIV** [comment]
ex1: amount is declared with var, answer is declared with let. Why? Just stick to let. Otherwise, this answer looks good.

Ex2: file isn't consistently formatted. Otherwise, looks good.

ex3: submit button should be of type 'submit'; yes this will require you to prevent the page from reloading.  I don't think it makes sense to use label elements for the error messages below the name and email fields, especially not when they appear empty at first.

ex4: numbers are not formatted with commas as indicated in the homework description. Otherwise, nice job.

**Pull request merged**
